[package]
name = "cw32f030-hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.7"
critical-section = "1.1.2"
vcell = "0.1.3"
